permalink: pretty
markdown: kramdown

title: The Accept Bitcoin Cash Initiative
author: n9jd34x04l151ho4 + topolino + kenman345
description:
    Community-curated list of sites/merchants that accept Bitcoin Cash.
url: https://usebitcoin.cash
repo: https://github.com/acceptbitcoincash/acceptbitcoincash
img: img/logo.png

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      # layout: "default"
      # Page Variables
      link_tweet: "Tweet to @TWITTERHANDLE"
      link_facebook: "Write on @FACEBOOKHANDLE's wall"
      email_subject: "Please%20consider%20accepting%20Bitcoin%20Cash%20payments"
      rtfm: "Read support docs from"
      link_mobile: "TWEET THEM"
      workonit_tweet: "Please consider accepting #BitcoinCash for payments @TWITTERHANDLE - itâ€™s \"Peer-to-Peer Electronic Cash\" that is fast, reliable, and secure, with low fees. More @"
      link_progress: "Thank them for accepting Bitcoin Cash"
      link_progress_mobile: "THANK THEM"
      progress_tweet: "Thanks for accepting Bitcoin Cash, @TWITTERHANDLE!"
      hash: "acceptBitcoinCash, BCHforEveryone"

exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
    - vendor
    - kube
    - nginx.conf
    - scripts
    - Dockerfile

theme: jekyll-theme-hacker
