permalink: pretty
markdown: kramdown

title: Two Factor Auth List
author: Josh Davis
description:
    List of sites with Two Factor Auth support which includes SMS, email,
    phone calls, hardware, and software.
url: http://twofactorauth.org
repo: https://github.com/jdavis/twofactorauth
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb

jekyll_sort:
    - src: websites
      by: name
      direction: up
      dest: websites_sorted
