permalink: pretty
markdown: kramdown

title: Two Factor Auth List
author: Josh Davis
description:
    List of sites with Two Factor Auth support which includes SMS, email,
    phone calls, hardware, and software.
url: http://twofactorauth.org
repo: https://github.com/2factorauth/twofactorauth
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
