permalink: pretty
markdown: kramdown

title: USB Dongle Auth List
author: Nitrokey
description:
    List of sites with support for USB dongle authentication which includes One Time Passwords (OTP) and Universal 2nd Factor (U2F).
url: http://dongleauth.info
uri: /dongleauth
repo: https://github.com/Nitrokey/dongleauth
img: img/logo.png

exclude:
    - CNAME
    - CONTRIBUTING.md
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
