---
websites:
-     name: CAcert
      url: https://www.cacert.org/
      twitter: CAcert_News
      img: cacert.png
      tfa: false
-     name: DigiCert
      url: http://www.digicert.com/
      twitter: digicert
      img: digicert.png
      tfa: false
      status: https://twitter.com/digicert/status/454722167897616384
-     name: Dome9 Security
      url: http://www.dome9.com/
      img: dome9.png
      tfa: true
      software: true
      hardware: true
      doc: http://www.dome9.com/overview/strong-2-factor-authentication
-     name: GeoTrust
      url: http://www.geotrust.com/
      img: geotrust.png
      tfa: true
      email: true
-     name: Norton
      url: http://us.norton.com
      img: norton.png
      tfa: true
      software: true
      sms: true
      phone: true
      doc: https://login.norton.com/sso/embedded/learn2fa
-     name: OpenDNS
      url: http://www.opendns.com/
      img: opendns.png
      tfa: true
      sms: true
      twitter: OpenDNS
      software: true
      exceptions:
            text: Only available for enterprise accounts.
      doc: http://engineering.opendns.com/2014/05/22/launching-two-step-verification/
-     name: SSLTrust
      url: http://ssltrust.com.au/
      img: ssltrust.png
      tfa: true
      software: true
      doc: http://www.ssltrust.com.au/enable-two-factor-authentication.html
-     name: ThreatMetrix
      url: https://www.threatmetrix.com/
      img: threatmetrix.png
      tfa: false
      twitter: ThreatMetrix
-     name: ThreatSim
      url: http://login.threatsim.com
      img: threatsim.png
      tfa: true
      sms: true
      doc: http://threatsim.com/features/
-     name: Tinfoil Security
      url: https://www.tinfoilsecurity.com
      img: tinfoil.png
      tfa: true
      software: true
      doc: http://support.tinfoilsecurity.com/customer/portal/articles/1559364-do-you-support-two-factor-authentication-how-do-i-set-it-up-
