websites:
  - name: AdGuard
    url: https://adguard.com
    img: adguard.png
    tfa:
      - totp
    doc: https://kb.adguard.com/en/general/2fa

  - name: Avast
    url: https://www.avast.com
    img: avast.png
    twitter: avast_antivirus
    facebook: avast

  - name: AVG
    url: https://www.avg.com
    img: avg.png
    twitter: AVGFree
    facebook: AVG

  - name: Bitdefender
    url: https://www.bitdefender.com
    img: bitdefender.png
    tfa:
      - email
      - totp
    doc: https://www.bitdefender.com/consumer/support/answer/1581/

  - name: BitSight
    url: https://service.bitsight.com
    img: bitsight.png
    tfa:
      - totp
    doc: https://help.bitsight.com/hc/en-us/articles/360057228514-BitSight-2-Factor-Authentication#bitsight_2fa

  - name: Blur
    url: https://www.abine.com/
    img: blur.png
    tfa:
      - totp
    doc: https://dnt.abine.com/#help/faq/faq-enabletwoFactor

  - name: Boxcryptor
    url: https://www.boxcryptor.com
    img: boxcryptor.png
    tfa:
      - totp
      - hardware
    doc: https://www.boxcryptor.com/help/boxcryptor-account/#two-factor-authentication

  - name: bugcrowd
    url: https://bugcrowd.com
    img: bugcrowd.png
    tfa:
      - totp
    doc: https://docs.bugcrowd.com/customers/role-and-account-management/two-factor-authentication/

  - name: CAcert
    url: http://www.cacert.org/
    img: cacert.png
    tfa:
      - hardware
    exception: "Requires X.509-capable cryptotoken or smartcard."

  - name: Cloudflare
    url: https://cloudflare.com
    img: cloudflare.png
    tfa:
      - totp
      - u2f
    doc: https://support.cloudflare.com/hc/en-us/articles/200167906

  - name: Cobalt
    url: https://cobalt.io/
    img: cobalt.png
    tfa:
      - totp
    doc: https://cobalt.io/blog/new-feature-two-factor-auth/

  - name: Detectify
    url: https://detectify.com/
    img: detectify.png
    tfa:
      - totp
    doc: https://support.detectify.com/support/solutions/articles/48001061904

  - name: DigiCert
    url: https://www.digicert.com/
    img: digicert.png
    tfa:
      - totp
    doc: https://www.digicert.com/two-factor-authentication.htm

  - name: DMARC Analyzer
    url: https://www.dmarcanalyzer.com/
    img: dmarcanalyzer.png
    tfa:
      - totp
    doc: https://www.dmarcanalyzer.com/set-two-factor-authentication-additional-security/

  - name: dmarcian
    url: https://dmarcian.com/
    img: dmarcian.png
    tfa:
      - totp
      - hardware
    doc: https://dmarcian.com/secure-dmarcian-2fa/

  - name: Dome9 Security
    url: https://dome9.com/
    img: dome9.png
    tfa:
      - totp
      - hardware
    doc: https://dome9.com/overview/strong-2-factor-authentication
  
  - name: EasyDMARC
    url: https://easydmarc.com
    img: easydmarc.png
    tfa:
      - totp
    doc: https://easydmarc.com/blog/two-factor-authentication/

  - name: Entrust
    img: entrust.png
    url: https://www.entrust.net
    tfa:
      - proprietary
      - hardware
    doc: https://www.entrust.com/multi-factor-authentication-tools/

  - name: ESET
    img: eset.png
    url: https://www.eset.com
    facebook: eset
    twitter: ESET

  - name: GeoTrust
    url: https://www.geotrust.com/
    img: geotrust.png
    tfa:
      - email

  - name: GoGetSSL
    url: https://gogetssl.com/
    img: gogetssl.png
    twitter: gogetssl
    facebook: gogetssl

  - name: HackerOne
    url: https://hackerone.com
    img: hackerone.png
    tfa:
      - totp
    doc: https://docs.hackerone.com/hackers/two-factor-authentication.html
    exception: SMS-capable phone required for initial setup.
    
  - name: hCaptcha
    url: https://hcaptcha.com
    img: hcaptcha.png
    twitter: hCaptcha
    facebook: hcaptcha
    email_address: support@hcaptcha.com

  - name: intigriti
    url: https://www.intigriti.com/
    img: intigriti.png
    tfa:
      - totp
    doc: https://kb.intigriti.com/en/articles/2642631

  - name: Kaspersky
    url: https://www.kaspersky.com/
    img: kaspersky.png
    tfa:
      - totp
      - sms
    doc: https://help.kaspersky.com/KPC/1.0/en-US/152628.htm

  - name: LexisNexis Risk Solutions
    url: https://risk.lexisnexis.com/
    img: lexisnexis.png
    twitter: LexisNexis
    facebook: lexisnexisus

  - name: McAfee
    url: https://www.mcafee.com/
    img: mcafee.png
    twitter: McAfee
    facebook: McAfee

  - name: Norton
    url: https://us.norton.com
    img: norton.png
    tfa:
      - sms
      - phone
      - proprietary
      - u2f
    doc: https://support.norton.com/sp/en/us/home/current/solutions/v100023155_NortonM_Retail_1_en_us

  - name: Panther
    url: https://runpanther.io
    img: panther.png
    tfa:
      - totp

  - name: Prey
    url: https://www.preyproject.com
    img: prey.png
    tfa:
      - totp
    doc: https://help.preyproject.com/article/248--

  - name: RBLTracker
    url: https://rbltracker.com/
    img: rbltracker.png
    tfa:
      - totp
    doc: https://rbltracker.com/docs/setting-up-two-factor-authentication/
    
  - name: SecurityTrails
    url: https://securitytrails.com/
    img: securitytrails.svg
    tfa:
      - totp
    doc: https://securitytrails.com/support/knowledge-base/two-factor-authentication-2fa-2/

  - name: Sophos Central
    url: https://www.sophos.com
    img: sophoscentral.png
    tfa:
      - email
      - totp
    doc: https://docs.sophos.com/central/Customer/help/en-us/central/Customer/concepts/ep_MultiFactorAuthentication.html

  - name: SSLTrust
    url: https://www.ssltrust.com.au/
    img: ssltrust.png
    tfa:
      - totp
    doc: https://www.ssltrust.com.au/help/account-management/enable-2factor

  - name: ThreatConnect
    url: https://threatconnect.com/
    img: threatconnect.png
    tfa:
      - totp
    doc: https://kb.threatconnect.com/customer/en/portal/articles/2214975

  - name: ThreatSim
    url: https://login.threatsim.com
    img: threatsim.png
    tfa:
      - sms

  - name: ThreatX
    url: https://www.threatx.com/
    img: threatx.png
    tfa:
      - totp
    doc: https://support.threatx.com/hc/en-us/articles/360022157591

  - name: Tinfoil Security
    url: https://www.tinfoilsecurity.com
    img: tinfoil.png
    tfa:
      - totp
    doc: https://support.tinfoilsecurity.com/article/43-do-you-support-two-factor-authentication-how-do-i-set-it-up

  - name: VirusTotal
    url: https://www.virustotal.com
    img: virustotal.png
    tfa:
      - totp

  - name: Webroot
    url: https://www.webroot.com
    img: webroot.png
    tfa:
      - totp
    doc: https://docs.webroot.com/us/en/home/wsa_website_userguide/wsa_managementwebsite_userguide.htm#GettingStarted/Enabling2-FactorAuthentication.htm
