websites:
    - name: CAcert
      url: https://www.cacert.org/
      twitter: CAcert_News
      img: cacert.png
      tfa: No

    - name: DigiCert
      url: https://www.digicert.com/
      twitter: digicert
      img: digicert.png
      tfa: No
      status: https://twitter.com/digicert/status/454722167897616384

    - name: Dome9 Security
      url: https://www.dome9.com/ 
      img: dome9.png
      tfa: Yes
      software: Yes
      hardware: Yes
      doc: http://www.dome9.com/overview/strong-2-factor-authentication 

    - name: GeoTrust
      url: https://www.geotrust.com/
      img: geotrust.png
      tfa: Yes
      email: Yes

    - name: Norton
      url: https://us.norton.com
      img: norton.png
      tfa: Yes
      software: Yes
      sms: Yes
      phone: Yes
      doc: https://login.norton.com/sso/embedded/learn2fa

    - name: SSLTrust
      url: http://ssltrust.com.au/
      img: ssltrust.png
      tfa: Yes
      software: Yes
      doc: http://www.ssltrust.com.au/enable-two-factor-authentication.html

    - name: ThreatSim
      url: https://login.threatsim.com
      img: threatsim.png
      tfa: Yes
      sms: Yes
      doc: https://threatsim.com/features/

    - name: Tinfoil Security
      url: https://www.tinfoilsecurity.com
      img: tinfoil.png
      tfa: Yes
      software: Yes
      doc: http://support.tinfoilsecurity.com/customer/portal/articles/1559364-do-you-support-two-factor-authentication-how-do-i-set-it-up-

    - name: ThreatMetrix
      url: https://www.threatmetrix.com/
      img: threatmetrix.png
      tfa: No
      twitter: ThreatMetrix

    - name: OpenDNS
      url: https://www.opendns.com/
      img: opendns.png
      tfa: Yes
      sms: Yes
      twitter: OpenDNS
      software: Yes
      doc: https://engineering.opendns.com/2014/05/22/launching-two-step-verification/
