websites:
    - name: AVG
      url: https://www.avg.com
      img: avg.png
      tfa: No
      twitter: AVGFree
      facebook: AVG

    - name: Bitdefender
      url: https://www.bitdefender.com
      img: bitdefender.png
      tfa: No
      twitter: Bitdefender
      facebook: bitdefender

    - name: Blur
      url: https://www.abine.com/
      img: blur.png
      tfa: Yes
      software: Yes
      doc: https://dnt.abine.com/#help/faq/faq-enabletwoFactor

    - name: Boxcryptor
      url: https://www.boxcryptor.com
      img: boxcryptor.png
      tfa: Yes
      software: Yes
      doc: https://www.boxcryptor.com/help/boxcryptor-account/#two-factor-authentication

    - name: bugcrowd
      url: https://bugcrowd.com
      img: bugcrowd.png
      tfa: Yes
      software: Yes
      doc: https://docs.bugcrowd.com/v1.0/docs/two-factor-authentication-1

    - name: CAcert
      url: http://www.cacert.org/
      img: cacert.png
      tfa: Yes
      hardware: Yes
      exceptions:
          text: "Requires X.509-capable cryptotoken or smartcard."

    - name: Cloudflare
      url: https://cloudflare.com
      img: cloudflare.png
      tfa: Yes
      software: Yes
      doc: https://support.cloudflare.com/hc/en-us/articles/200167866-How-do-I-set-up-two-factor-authentication-

    - name: Cobalt
      url: https://cobalt.io/
      img: cobalt.png
      tfa: Yes
      software: Yes
      doc: https://cobalt.io/blog/new-feature-two-factor-auth/

    - name: Detectify
      url: https://detectify.com/
      img: detectify.png
      twitter: detectify
      facebook: detectify
      email_address: hello@detectify.com
      tfa: No

    - name: DigiCert
      url: https://www.digicert.com/
      img: digicert.png
      tfa: Yes
      software: Yes
      doc: https://www.digicert.com/two-factor-authentication.htm

    - name: Dome9 Security
      url: https://dome9.com/
      img: dome9.png
      tfa: Yes
      software: Yes
      hardware: Yes
      doc: https://dome9.com/overview/strong-2-factor-authentication

    - name: Entrust
      img: entrust.png
      url: https://www.entrust.net
      tfa: Yes
      software: Yes
      hardware: Yes
      doc: http://www.entrust.net/certificate-services/cms-authentication.htm

    - name: ESET
      img: eset.png
      url: https://www.eset.com
      tfa: No
      facebook: eset
      twitter: ESET

    - name: GeoTrust
      url: https://www.geotrust.com/
      img: geotrust.png
      tfa: Yes
      email: Yes

    - name: GoGetSSL
      url: https://gogetssl.com/
      img: gogetssl.png
      tfa: No
      twitter: gogetssl
      facebook: gogetssl

    - name: HackerOne
      url: https://hackerone.com
      img: hackerone.png
      tfa: Yes
      software: Yes
      doc: https://docs.hackerone.com/hackers/two-factor-authentication.html
      exceptions:
          text: "SMS-capable phone required for initial setup."

    - name: McAfee
      url: https://www.mcafee.com/
      img: mcafee.png
      tfa: No
      twitter: mcafee
      facebook: McAfee

    - name: Norton
      url: https://us.norton.com
      img: norton.png
      tfa: Yes
      software: Yes
      hardware: Yes
      sms: Yes
      phone: Yes
      doc: https://support.norton.com/sp/en/us/home/current/solutions/v100023155_NortonM_Retail_1_en_us

    - name: Prey
      url: https://www.preyproject.com
      img: prey.png
      tfa: Yes
      software: Yes
      doc: http://help.preyproject.com/article/248-how-to-enable-the-two-step-authenticator-for-prey

    - name: Pwnie Express Pwn Pulse
      url: https://www.pwnieexpress.com/products/pulse-device-detection
      img: pwnieexpress.png
      tfa: Yes
      software: Yes
      exceptions:
          text: "TFA can be enabled on Pwn Pulse Accounts upon customer request."
      doc: http://support.pwnieexpress.com/customer/en/portal/articles/2858909-chapter-5-pulse-administration-user-management

    - name: RBLTracker
      url: https://rbltracker.com/
      img: rbltracker.png
      tfa: Yes
      software: Yes
      doc: https://rbltracker.com/docs/setting-up-two-factor-authentication/

    - name: Sophos Central
      url: https://www.sophos.com
      img: sophoscentral.png
      tfa: Yes
      software: Yes
      email: Yes
      doc: https://docs.sophos.com/central/Customer/help/en-us/central/Customer/concepts/ep_MultiFactorAuthentication.html

    - name: SSLTrust
      url: https://www.ssltrust.com.au/
      img: ssltrust.png
      tfa: Yes
      software: Yes
      doc: http://www.ssltrust.com.au/enable-two-factor-authentication.html

    - name: Surfshark
      url: https://surfshark.com/
      img: surfshark.png
      tfa: No
      twitter: SurfsharkSecure
      facebook: SurfsharkPrivacy

    - name: ThreatConnect
      url: https://threatconnect.com/
      img: threatconnect.png
      tfa: Yes
      software: Yes
      doc: http://kb.threatconnect.com/customer/en/portal/articles/2214975-configuring-user-settings-and-two-factor-authentication

    - name: ThreatMetrix
      url: https://www.threatmetrix.com/
      img: threatmetrix.png
      tfa: No
      twitter: ThreatMetrix

    - name: ThreatSim
      url: https://login.threatsim.com
      img: threatsim.png
      tfa: Yes
      sms: Yes

    - name: ThreatX
      url: https://www.threatx.com/
      img: threatx.png
      tfa: Yes
      software: Yes
      doc: https://support.threatx.com/hc/en-us/articles/360022157591

    - name: Tinfoil Security
      url: https://www.tinfoilsecurity.com
      img: tinfoil.png
      tfa: Yes
      software: Yes
      doc: http://support.tinfoilsecurity.com/customer/portal/articles/1559364-do-you-support-two-factor-authentication-how-do-i-set-it-up-

    - name: TorGuard
      url: https://torguard.net
      img: torguard.png
      tfa: Yes
      software: Yes

    - name: Webroot
      url: https://www.webroot.com
      img: webroot.png
      twitter: Webroot
      facebook: Webroot
      tfa: No
