websites:
    - name: 143VPN
      url: https://143vpn.com
      img: 143VPN.png
      twitter: 143VPN
      facebook: 143VPN
      bch: Yes
      btc: Yes
      othercrypto: Yes

    - name: Air VPN
      url: https://airvpn.org/
      img: airvpn.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
      twitter: airvpn
      facebook: airvpn.org

    - name: Anonine
      url: https://anonine.com
      img: anonine.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
      twitter: anoninevpn
      facebook: Anonine

    - name: AstrillVPN
      url: https://anonine.com
      img: astrill.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
      twitter: astrill
      facebook: astrillvpn

    - name: Blur
      url: https://www.abine.com/
      img: blur.png
      bch: No
      twitter: Abine
      facebook: AbineInc

    - name: BolehVPN
      url: https://www.bolehvpn.net/
      img: bolehvpn.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
      twitter: bolehvpn

    - name: CAcert
      url: http://www.cacert.org/
      img: cacert.png
      bch: No
      twitter: CAcert
      email_address: support@cacert.org

    - name: Cobalt
      url: https://cobalt.io/
      img: cobalt.png
      bch: No
      twitter: cobalt_io
      facebook: cobaltsecured

    - name: CrypticVPN
      url: https://crypticvpn.com
      img: crypticvpn.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
      twitter: CrypticVPN

    - name: CyberGhost
      url: https://www.cyberghostvpn.com
      img: cyberghost.png
      bch: No
      twitter: cyberghost_EN
      facebook: cyberghostEN

    - name: Detectify
      url: https://detectify.com/
      img: detectify.png
      bch: No
      twitter: detectify
      facebook: detectify
      email_address: hello@detectify.com

    - name: DigiCert
      url: https://www.digicert.com/
      img: digicert.png
      bch: No
      twitter: digicert
      facebook: digicert

    - name: Dome9 Security
      url: https://dome9.com/
      img: dome9.png
      bch: No
      twitter: dome9
      facebook: Dome9Security

    - name: Earth VPN
      url: http://www.earthvpn.com/
      img: earthvpn.png
      twitter: Earthvpn
      facebook: Earthvpn
      bch: Yes
      btc: Yes
      othercrypto: No

    - name: Entrust
      img: entrust.png
      url: https://www.entrust.net
      bch: No
      twitter: EntrustDatacard
      facebook: EntrustDatacard

    - name: ExpressVPN
      img: expressvpn.png
      url: https://www.expressvpn.com
      bch: No
      btc: Yes
      twitter: expressvpn
      facebook: ExpressVPN

    - name: GeoTrust
      url: https://www.geotrust.com/
      img: geotrust.png
      bch: No
      twitter: geotrust
      facebook: Geotrust

    - name: GoGetSSL
      url: https://gogetssl.com/
      img: gogetssl.png
      bch: No
      twitter: gogetssl
      facebook: gogetssl

    - name: hide.me VPN
      url: https://hide.me/
      img: hidemevpn.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
      twitter: thevpncompany
      facebook: www.hide.me

    - name: IPVanish
      url: https://www.ipvanish.com
      img: ipvanish.png
      bch: No
      btc: No
      twitter: ipvanish
      facebook: ipvanish

    - name: Mullvad VPN
      url: https://mullvad.net/
      twitter: mullvadnet
      email_address: support@mullvad.net
      img: mullvad.png
      bch: yes
      btc: yes
      othercrypto: no
      doc: https://mullvad.net/en/blog/2018/2/13/bitcoin-cash-now-accepted/

    - name: NordVPN
      url: https://www.nordvpn.com
      img: nordvpn.png
      bch: No
      btc: Yes
      othercrypto: Yes
      twitter: nordvpn
      facebook: NordVPN

    - name: nVpn
      url: https://nvpn.net/
      img: nvpn.png
      twitter: nVpnNet
      bch: Yes
      btc: Yes
      othercrypto: Yes

    - name: OpenDNS
      url: https://www.opendns.com/
      img: opendns.png
      bch: No
      twitter: opendns
      facebook: OpenDNS

    - name: Perfect Privacy VPN
      url: https://www.perfect-privacy.com/
      img: perfectprivacyvpn.png
      bch: Yes
      btc: Yes
      othercrypto: No
      twitter: perfectprivacy
      facebook: perfect.privacy

    - name: Premiumize.me
      url: https://www.premiumize.me
      img: premiumizeme.png
      twitter: premiumizeme
      facebook: PremiumizeMe
      email_address: acceptbitcoin@guyrimmer.com
      bch: Yes
      btc: Yes
      othercrypto: Yes

    - name: Prey
      url: https://www.preyproject.com
      img: prey.png
      bch: No
      twitter: preyproject
      facebook: preyproject

    - name: Private Internet Access
      url: https://www.privateinternetaccess.com
      img: privateinternetaccess.png
      bch: Yes
      btc: Yes
      twitter: piacsm

    - name: ProtonVPN
      url: https://protonvpn.com/
      img: protonvpn.png
      bch: No
      btc: Yes
      twitter: ProtonVPN
      facebook: ProtonVPN

    - name: PureVPN
      url: https://www.purevpn.com
      img: purevpn.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
      twitter: purevpn
      facebook: PureVPNcom

    - name: Pwnie Express Pwn Pulse
      url: https://www.pwnieexpress.com/products/pulse-device-detection
      img: pwnieexpress.png
      bch: No
      twitter: pwnieexpress
      facebook: Pwnie.Express.Pentesting

    - name: RBLTracker
      url: https://rbltracker.com/
      img: rbltracker.png
      bch: No
      twitter: rbltracker
      facebook: rbltracker

    - name: SaferVPN
      url: https://www.safervpn.com
      img: safervpn.png
      bch: No
      btc: Yes
      twitter: safervpn
      facebook: SaferVPNCom

    - name: ShadeYou
      url: https://shadeyouvpn.com/
      img: shadeyou.png
      bch: No
      btc: Yes
      twitter: shadeyou_vpn
      facebook: shadeyouvpn

    - name: SigaVPN
      region: na
      country: us
      url: https://sigavpn.com
      img: sigavpn.png
      bch: yes
      btc: yes
      othercrypto: yes

    - name: Snusbase
      url: https://snusbase.com
      twitter: publicdbhost
      img: snusbase.png
      bch: yes
      btc: yes
      othercrypto: yes

    - name: SSLTrust
      url: https://www.ssltrust.com.au/
      img: ssltrust.png
      bch: No
      twitter: ssltrust
      facebook: ssltrust

    - name: The Keyois Capsule
      url: https://keyois.com/
      img: keyois.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/btc/comments/6t15gd/keyoiscom_makers_of_the_keyois_capsule_now/

    - name: ThreatConnect
      url: https://threatconnect.com/
      img: threatconnect.png
      bch: No
      twitter: ThreatConnect
      facebook: ThreatConnect

    - name: ThreatMetrix
      url: https://www.threatmetrix.com/
      img: threatmetrix.png
      bch: No
      twitter: ThreatMetrix

    - name: ThreatSim
      url: https://login.threatsim.com
      img: threatsim.png
      bch: No
      twitter: WombatSecurity
      facebook: Wombat-Security-Technologies-272945251150

    - name: Tinfoil Security
      url: https://www.tinfoilsecurity.com
      img: tinfoil.png
      bch: No
      twitter: tinfoilsecurity
      facebook: tinfoilsecurity

    - name: TorGuard
      url: https://torguard.net
      img: torguard.png
      bch: No
      btc: Yes
      othercrypto: Yes
      twitter: TorGuard
      facebook: TorGuard

    - name: TunnelBear
      url: https://tunnelbear.com/
      img: tunnelbear.png
      bch: Yes
      btc: Yes
      twitter: theTunnelBear
      facebook: tunnelbear

    - name: VPN Unlimited
      url: https://vpnunlimitedapp.com/
      img: vpnunlimited.png
      twitter: vpnunlimited
      facebook: vpnunlimitedapp
      bch: Yes
      btc: Yes
      othercrypto: No

    - name: vpn.ac
      url: https://vpn.ac/
      img: vpnac.png
      bch: Yes
      btc: Yes
      othercrypto: Yes

    - name: Windscribe
      url: https://windscribe.com
      img: windscribe.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
      twitter: windscribecom
      facebook: windscribe
