---
websites:
- name: 143VPN
  url: https://143vpn.com
  img: 143VPN.png
  twitter: 143VPN
  facebook: 143VPN
  bch: true
  btc: true
  othercrypto: true
- name: 4everproxy
  url: https://www.4everproxy.com
  img: everproxy.png
  bch: true
  btc: true
  othercrypto: true
  twitter: 4everproxy
  facebook: 4everproxy
  email_address: hello@4everproxy.com
  doc: https://twitter.com/4everproxy/status/1263261808300896257
  keywords:
  - coinpayments.net
- name: Air VPN
  url: https://airvpn.org/
  img: airvpn.png
  bch: true
  btc: true
  othercrypto: true
  twitter: airvpn
  facebook: airvpn.org
- name: Anonine
  url: https://anonine.com
  img: anonine.png
  bch: true
  btc: true
  othercrypto: true
  twitter: anoninevpn
  facebook: Anonine
- name: AstrillVPN
  url: https://www.astrill.com
  img: astrill.png
  bch: true
  btc: true
  othercrypto: true
  twitter: astrill
  facebook: astrillvpn
  keywords:
  - coinpayments.net
- name: Avira
  img: avira.png
  url: https://www.avira.com
  bch: true
  btc: true
  othercrypto: true
  twitter: avira
  facebook: avira
  keywords:
  - bitpay
  exceptions:
    text: Bitcoin is accepted for Phantom VPN Pro only
- name: BA.net AdBlock VPN
  url: https://ba.net/adblockvpn
  img: BAnetAdBlockVPN.png
  bch: true
  btc: false
  othercrypto: false
  email_address: adblock@ba.net
- name: Bitwarden
  url: https://bitwarden.com/
  img: bitwarden.png
  bch: true
  btc: true
  othercrypto: true
  doc: https://blog.bitwarden.com/now-accepting-bitcoin-11bdf6e04ad1
  keywords:
  - bitpay
- name: Blur
  url: https://www.abine.com/
  img: blur.png
  bch: false
  twitter: Abine
  facebook: AbineInc
- name: BolehVPN
  url: https://www.bolehvpn.net/
  img: bolehvpn.png
  bch: true
  btc: true
  othercrypto: true
  twitter: bolehvpn
  keywords:
  - bitpay
  - coinpayments.net
- name: BulletVPN
  url: https://www.bulletvpn.com/
  img: bulletvpn.png
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - bitpay
- name: CAcert
  url: http://www.cacert.org/
  img: cacert.png
  bch: false
  twitter: CAcert
  email_address: support@cacert.org
- name: Cobalt
  url: https://cobalt.io/
  img: cobalt.png
  bch: false
  twitter: cobalt_io
  facebook: cobaltsecured
- name: CrypticVPN
  url: https://crypticvpn.com
  img: crypticvpn.png
  bch: true
  btc: true
  othercrypto: true
  twitter: CrypticVPN
- name: CyberGhost
  url: https://www.cyberghostvpn.com/
  img: cyberghost.png
  bch: true
  btc: true
  othercrypto: true
  twitter: cyberghost_EN
  facebook: cyberghostEN
  keywords:
  - bitpay
- name: Detectify
  url: https://detectify.com/
  img: detectify.png
  bch: false
  twitter: detectify
  facebook: detectify
  email_address: hello@detectify.com
- name: DigiCert
  url: https://www.digicert.com/
  img: digicert.png
  bch: false
  twitter: digicert
  facebook: digicert
- name: Dome9 Security
  url: https://dome9.com/
  img: dome9.png
  bch: false
  twitter: dome9
  facebook: Dome9Security
- name: Earth VPN
  url: http://www.earthvpn.com/
  img: earthvpn.png
  twitter: Earthvpn
  facebook: Earthvpn
  bch: true
  btc: true
  othercrypto: false
- name: Entrust
  img: entrust.png
  url: https://www.entrust.net
  bch: false
  twitter: EntrustDatacard
  facebook: EntrustDatacard
- name: ExpressVPN
  img: expressvpn.png
  url: https://www.expressvpn.com
  bch: false
  btc: true
  othercrypto: true
  twitter: expressvpn
  facebook: ExpressVPN
  keywords:
  - bitpay
- name: Firo Solutions
  url: https://firosolutions.com
  img: FiroSolutions.png
  bch: true
  btc: true
  othercrypto: true
  twitter: firosolutions
  email_address: info@firosolutions.com
- name: GeoTrust
  url: https://www.geotrust.com/
  img: geotrust.png
  bch: false
  twitter: geotrust
  facebook: Geotrust
- name: GoGetSSL
  url: https://gogetssl.com/
  img: gogetssl.png
  bch: false
  twitter: gogetssl
  facebook: gogetssl
- name: Hide My IP
  url: https://www.hide-my-ip.com/
  img: hidemyip.png
  twitter: hidemyip
  facebook: hidemyip
  email_address: staff@hide-my-ip.com
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - bitpay
- name: hide.me VPN
  url: https://hide.me/
  img: hidemevpn.png
  bch: true
  btc: true
  othercrypto: true
  twitter: thevpncompany
  facebook: www.hide.me
- name: ibVPN
  url: https://www.ibvpn.com/
  img: ibvpn.png
  twitter: ibvpn
  facebook: ibVPN
  btc: true
  bch: true
  othercrypto: true
  keywords:
  - bitpay
  - coinpayments.net
- name: InterSSL
  url: https://www.interssl.com/
  img: interssl.png
  btc: true
  bch: true
  othercrypto: true
  facebook: interssl
  keywords:
  - bitpay
- name: IPVanish
  url: https://www.ipvanish.com
  img: ipvanish.png
  bch: false
  btc: false
  twitter: ipvanish
  facebook: ipvanish
- name: IronSocket
  url: https://ironsocket.com/
  img: ironsocket.png
  twitter: ironsocket
  facebook: ironsocket
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - bitpay
- name: Ivacy VPN
  url: https://www.ivacy.com/
  img: ivacyvpn.png
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - bitpay
  - coinpayments.net
- name: IVPN
  url: https://www.ivpn.net/
  img: ivpn.png
  twitter: ivpnnet
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - bitpay
- name: LiquidVPN
  url: https://www.liquidvpn.com/
  img: liquidvpn.png
  twitter: LiquidVPN
  facebook: LiquidVPN
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - bitpay
- name: Mullvad VPN
  url: https://mullvad.net/
  twitter: mullvadnet
  email_address: support@mullvad.net
  img: mullvad.png
  bch: true
  btc: true
  othercrypto: false
  doc: https://mullvad.net/en/blog/2018/2/13/bitcoin-cash-now-accepted/
- name: MultiVPN
  url: https://multi-vpn.biz/
  img: multivpn.png
  twitter: multivpn
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - coinpayments.net
- name: NordVPN
  url: https://www.nordvpn.com
  img: nordvpn.png
  bch: true
  btc: true
  othercrypto: true
  twitter: nordvpn
  facebook: NordVPN
  keywords:
  - coinpayments.net
- name: nVpn
  url: https://nvpn.net/
  img: nvpn.png
  twitter: nVpnNet
  facebook: nvpn.net
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - coinpayments.net
- name: OpenDNS
  url: https://www.opendns.com/
  img: opendns.png
  bch: false
  twitter: opendns
  facebook: OpenDNS
- name: oVPN Anonymous Services
  url: https://vcp.ovpn.to
  img: oVPNAnon.png
  bch: true
  btc: true
  othercrypto: true
- name: OVPN Integritet AB
  url: https://www.ovpn.com
  img: OVPNIntegritetAB.png
  bch: true
  btc: true
  othercrypto: true
  twitter: ovpn_official
  email_address: support@ovpn.com
  keywords:
  - bitpay
- name: Perfect Privacy VPN
  url: https://www.perfect-privacy.com/
  img: perfectprivacyvpn.png
  bch: true
  btc: true
  othercrypto: false
  twitter: perfectprivacy
  facebook: perfect.privacy
- name: PlasmaVPN
  url: https://plasmavpn.com
  img: PlasmaVPN.png
  bch: true
  btc: true
  othercrypto: true
  email_address: pokkst@tutanota.com
  exceptions:
    text: Currently in BETA
- name: Premiumize.me
  url: https://www.premiumize.me
  img: premiumizeme.png
  twitter: premiumizeme
  facebook: PremiumizeMe
  email_address: acceptbitcoin@guyrimmer.com
  bch: true
  btc: true
  othercrypto: true
- name: Prey
  url: https://www.preyproject.com
  img: prey.png
  bch: false
  twitter: preyproject
  facebook: preyproject
- name: Private Internet Access
  url: https://www.privateinternetaccess.com
  img: privateinternetaccess.png
  bch: true
  btc: true
  othercrypto: true
  twitter: piacsm
  keywords:
  - bitpay
- name: ProtonVPN
  url: https://protonvpn.com/
  img: protonvpn.png
  bch: false
  btc: true
  twitter: ProtonVPN
  facebook: ProtonVPN
- name: PureVPN
  url: https://www.purevpn.com
  img: purevpn.png
  bch: true
  btc: true
  othercrypto: true
  facebook: PureVPNcom
  keywords:
  - coinpayments.net
  exceptions:
    text: No refunds for cryptocurrency
- name: Pwnie Express Pwn Pulse
  url: https://www.pwnieexpress.com/products/pulse-device-detection
  img: pwnieexpress.png
  bch: false
  twitter: pwnieexpress
  facebook: Pwnie.Express.Pentesting
- name: RBLTracker
  url: https://rbltracker.com/
  img: rbltracker.png
  bch: false
  twitter: rbltracker
  facebook: rbltracker
- name: SaferVPN
  url: https://www.safervpn.com
  img: safervpn.png
  twitter: safervpn
  facebook: SaferVPNCom
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - coingate
- name: SecPoint
  url: https://shop.secpoint.com
  img: SecPoint.png
  bch: true
  btc: true
  othercrypto: true
  twitter: secpoint
  facebook: secpoint
  email_address: brian@secpoint.com
- name: ShadeYou
  url: https://shadeyouvpn.com/
  img: shadeyou.png
  bch: false
  btc: true
  twitter: shadeyou_vpn
  facebook: shadeyouvpn
- name: Shellfire
  url: https://www.shellfire.de/
  img: shellfire.png
  twitter: shellfire_de
  facebook: shellfire.de
  email_address: hosting@shellfire.de
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - bitpay
- name: SigaVPN
  region: na
  country: us
  url: https://sigavpn.com
  img: sigavpn.png
  bch: true
  btc: true
  othercrypto: true
- name: SlickVPN
  url: https://www.slickvpn.com/
  img: slickvpn.png
  twitter: slickvpn
  facebook: slickvpn
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - bitpay
- name: Snusbase
  url: https://snusbase.com
  twitter: publicdbhost
  img: snusbase.png
  bch: true
  btc: true
  othercrypto: true
- name: SSLTrust
  url: https://www.ssltrust.com.au/
  img: ssltrust.png
  btc: true
  bch: true
  othercrypto: true
  twitter: SSLTrust
  facebook: ssltrust
  doc: https://twitter.com/SSLTrust/status/925511573673783296
  keywords:
  - coinpayments.net
  exceptions:
    text: No refunds for cryptocurrency, only store credit
- name: Surfshark
  url: https://surfshark.com
  img: surfshark.png
  twitter: Surfshark
  facebook: SurfsharkPrivacy
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - coinpayments.net
  - coingate
- name: The Keyois Capsule
  url: https://keyois.com/
  img: keyois.png
  bch: true
  btc: true
  othercrypto: true
  doc: https://www.reddit.com/r/btc/comments/6t15gd/keyoiscom_makers_of_the_keyois_capsule_now/
- name: ThreatConnect
  url: https://threatconnect.com/
  img: threatconnect.png
  bch: false
  twitter: ThreatConnect
  facebook: ThreatConnect
- name: ThreatMetrix
  url: https://www.threatmetrix.com/
  img: threatmetrix.png
  bch: false
  twitter: ThreatMetrix
- name: ThreatSim
  url: https://login.threatsim.com
  img: threatsim.png
  bch: false
  twitter: WombatSecurity
  facebook: Wombat-Security-Technologies-272945251150
- name: Tinfoil Security
  url: https://www.tinfoilsecurity.com
  img: tinfoil.png
  bch: false
  twitter: tinfoilsecurity
  facebook: tinfoilsecurity
- name: TorGuard
  url: https://torguard.net
  img: torguard.png
  bch: false
  btc: true
  othercrypto: true
  twitter: TorGuard
  facebook: TorGuard
- name: TunnelBear
  url: https://tunnelbear.com/
  img: tunnelbear.png
  bch: true
  btc: true
  twitter: theTunnelBear
  facebook: tunnelbear
- name: VPN SURF
  url: https://vpn.surf
  img: vpnsurf.png
  email_address: sales@vpn.surf
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - coinpayments
- name: VPN Unlimited
  url: https://vpnunlimitedapp.com/
  img: vpnunlimited.png
  twitter: vpnunlimited
  facebook: vpnunlimitedapp
  bch: true
  btc: true
  othercrypto: false
- name: vpn.ac
  url: https://vpn.ac/
  img: vpnac.png
  bch: true
  btc: true
  othercrypto: true
  doc: https://vpn.ac/announcements/51/Bitcoin-payments-through-BitPay-suspended.html
  keywords:
  - coinpayments.net
  - bitpay
- name: VPNArea
  url: https://vpnarea.com/
  img: vpnarea.png
  twitter: vpnareacom
  facebook: vpnarea
  bch: true
  btc: true
  othercrypto: true
  keywords:
  - bitpay
- name: Windscribe
  url: https://windscribe.com
  img: windscribe.png
  bch: true
  btc: true
  othercrypto: true
  twitter: windscribecom
  facebook: windscribe
