websites:
    - name: Gutes Leben Ltd
      url: https://guteshome.com/
      img: guteslebenltd.png
      twitter: guteslebenltd
      facebook: guteslebenItd.
      email_address: gutesleben@consultant.com
      region: af
      country: GH
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
      
    - name: KNW refrigeration
      url: http://www.knw-refrigeration.co.za
      img: knwRefrigeration.png
      email_address: info@knw-refrigeration.co.za
      region: af
      country: ZA
      city: Cape Town
      bch: Yes
      btc: Yes
      othercrypto: No

    - name: medical valuations
      url: https://medicalvaluations.com
      img: medicalValuations.png
      region: na
      country: US
      city: Scottsdale
      twitter: medicalval
      facebook: MVincRoss
      bch: yes
      btc: yes
      
    - name: PekTech
      url: https://pek.tech
      img: pektech.png
      twitter: pek_tech
      email_address: contact@pek.tech
      region: na
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://twitter.com/pek_tech/status/962967524605231104
      
    - name: Ponti Partners
      url: https://pontipartners.com.au/
      img: pontipartners.png
      facebook: pontipartners
      region: oc
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/7rht8s/bitcoin_cash_moving_beyond_just_merchant_adoption/
      
    - name: Spatial Simulations
      url: https://www.spatialsim.com/
      img: spatialsimulations.png
      email_address: 3d@spatialsim.com
      bch: Yes
      btc: Yes
      othercrypto: Yes