blank_issues_enabled: false
contact_links:
  - name: ðŸš¨ 8. Report a code of conduct violation
    url: https://github.com/2factorauth/twofactorauth/blob/master/CODE_OF_CONDUCT.md#enforcement
    about: Review the enforcement section of our code of conduct to report a violation.
